// Generado por tools/zarpa_data/countries_ts.py (CLDR + regiones de GBIF). No editar a mano.
export type Region = 'AFRICA' | 'ANTARCTICA' | 'ASIA' | 'EUROPE' | 'LATIN_AMERICA' | 'NORTH_AMERICA' | 'OCEANIA';

export const REGION_LABEL: Record<Region, string> = {
  "AFRICA": "África",
  "ANTARCTICA": "Antártida",
  "ASIA": "Asia",
  "EUROPE": "Europa",
  "LATIN_AMERICA": "Latinoamérica y Caribe",
  "NORTH_AMERICA": "Norteamérica",
  "OCEANIA": "Oceanía"
};

export const COUNTRIES: { cc: string; name: string; region: Region | null }[] = [
  { cc: 'AF', name: "Afganistán", region: "ASIA" },
  { cc: 'AL', name: "Albania", region: "EUROPE" },
  { cc: 'DE', name: "Alemania", region: "EUROPE" },
  { cc: 'AD', name: "Andorra", region: "EUROPE" },
  { cc: 'AO', name: "Angola", region: "AFRICA" },
  { cc: 'AI', name: "Anguila", region: "LATIN_AMERICA" },
  { cc: 'AG', name: "Antigua y Barbuda", region: "LATIN_AMERICA" },
  { cc: 'AQ', name: "Antártida", region: "ANTARCTICA" },
  { cc: 'SA', name: "Arabia Saudí", region: "ASIA" },
  { cc: 'DZ', name: "Argelia", region: "AFRICA" },
  { cc: 'AR', name: "Argentina", region: "LATIN_AMERICA" },
  { cc: 'AM', name: "Armenia", region: "EUROPE" },
  { cc: 'AW', name: "Aruba", region: "LATIN_AMERICA" },
  { cc: 'AU', name: "Australia", region: "OCEANIA" },
  { cc: 'AT', name: "Austria", region: "EUROPE" },
  { cc: 'AZ', name: "Azerbaiyán", region: "EUROPE" },
  { cc: 'BS', name: "Bahamas", region: "LATIN_AMERICA" },
  { cc: 'BD', name: "Bangladés", region: "ASIA" },
  { cc: 'BB', name: "Barbados", region: "LATIN_AMERICA" },
  { cc: 'BH', name: "Baréin", region: "ASIA" },
  { cc: 'BZ', name: "Belice", region: "LATIN_AMERICA" },
  { cc: 'BJ', name: "Benín", region: "AFRICA" },
  { cc: 'BM', name: "Bermudas", region: "LATIN_AMERICA" },
  { cc: 'BY', name: "Bielorrusia", region: "EUROPE" },
  { cc: 'BO', name: "Bolivia", region: "LATIN_AMERICA" },
  { cc: 'BA', name: "Bosnia y Herzegovina", region: "EUROPE" },
  { cc: 'BW', name: "Botsuana", region: "AFRICA" },
  { cc: 'BR', name: "Brasil", region: "LATIN_AMERICA" },
  { cc: 'BN', name: "Brunéi", region: "ASIA" },
  { cc: 'BG', name: "Bulgaria", region: "EUROPE" },
  { cc: 'BF', name: "Burkina Faso", region: "AFRICA" },
  { cc: 'BI', name: "Burundi", region: "AFRICA" },
  { cc: 'BT', name: "Bután", region: "ASIA" },
  { cc: 'BE', name: "Bélgica", region: "EUROPE" },
  { cc: 'CV', name: "Cabo Verde", region: "AFRICA" },
  { cc: 'KH', name: "Camboya", region: "ASIA" },
  { cc: 'CM', name: "Camerún", region: "AFRICA" },
  { cc: 'CA', name: "Canadá", region: "NORTH_AMERICA" },
  { cc: 'BQ', name: "Caribe neerlandés", region: "LATIN_AMERICA" },
  { cc: 'QA', name: "Catar", region: "ASIA" },
  { cc: 'TD', name: "Chad", region: "AFRICA" },
  { cc: 'CZ', name: "Chequia", region: "EUROPE" },
  { cc: 'CL', name: "Chile", region: "LATIN_AMERICA" },
  { cc: 'CN', name: "China", region: "ASIA" },
  { cc: 'CY', name: "Chipre", region: "EUROPE" },
  { cc: 'VA', name: "Ciudad del Vaticano", region: "EUROPE" },
  { cc: 'CO', name: "Colombia", region: "LATIN_AMERICA" },
  { cc: 'KM', name: "Comoras", region: "AFRICA" },
  { cc: 'CG', name: "Congo", region: "AFRICA" },
  { cc: 'KP', name: "Corea del Norte", region: "ASIA" },
  { cc: 'KR', name: "Corea del Sur", region: "ASIA" },
  { cc: 'CR', name: "Costa Rica", region: "LATIN_AMERICA" },
  { cc: 'HR', name: "Croacia", region: "EUROPE" },
  { cc: 'CU', name: "Cuba", region: "LATIN_AMERICA" },
  { cc: 'CW', name: "Curazao", region: "LATIN_AMERICA" },
  { cc: 'CI', name: "Côte d’Ivoire", region: "AFRICA" },
  { cc: 'DK', name: "Dinamarca", region: "EUROPE" },
  { cc: 'DM', name: "Dominica", region: "LATIN_AMERICA" },
  { cc: 'EC', name: "Ecuador", region: "LATIN_AMERICA" },
  { cc: 'EG', name: "Egipto", region: "AFRICA" },
  { cc: 'SV', name: "El Salvador", region: "LATIN_AMERICA" },
  { cc: 'AE', name: "Emiratos Árabes Unidos", region: "ASIA" },
  { cc: 'ER', name: "Eritrea", region: "AFRICA" },
  { cc: 'SK', name: "Eslovaquia", region: "EUROPE" },
  { cc: 'SI', name: "Eslovenia", region: "EUROPE" },
  { cc: 'ES', name: "España", region: "EUROPE" },
  { cc: 'US', name: "Estados Unidos", region: "NORTH_AMERICA" },
  { cc: 'EE', name: "Estonia", region: "EUROPE" },
  { cc: 'SZ', name: "Esuatini", region: "AFRICA" },
  { cc: 'ET', name: "Etiopía", region: "AFRICA" },
  { cc: 'PH', name: "Filipinas", region: "ASIA" },
  { cc: 'FI', name: "Finlandia", region: "EUROPE" },
  { cc: 'FJ', name: "Fiyi", region: "OCEANIA" },
  { cc: 'FR', name: "Francia", region: "EUROPE" },
  { cc: 'GA', name: "Gabón", region: "AFRICA" },
  { cc: 'GM', name: "Gambia", region: "AFRICA" },
  { cc: 'GE', name: "Georgia", region: "EUROPE" },
  { cc: 'GH', name: "Ghana", region: "AFRICA" },
  { cc: 'GI', name: "Gibraltar", region: "EUROPE" },
  { cc: 'GD', name: "Granada", region: "LATIN_AMERICA" },
  { cc: 'GR', name: "Grecia", region: "EUROPE" },
  { cc: 'GL', name: "Groenlandia", region: "NORTH_AMERICA" },
  { cc: 'GP', name: "Guadalupe", region: "LATIN_AMERICA" },
  { cc: 'GU', name: "Guam", region: "OCEANIA" },
  { cc: 'GT', name: "Guatemala", region: "LATIN_AMERICA" },
  { cc: 'GF', name: "Guayana Francesa", region: "LATIN_AMERICA" },
  { cc: 'GG', name: "Guernesey", region: "EUROPE" },
  { cc: 'GN', name: "Guinea", region: "AFRICA" },
  { cc: 'GQ', name: "Guinea Ecuatorial", region: "AFRICA" },
  { cc: 'GW', name: "Guinea-Bisáu", region: "AFRICA" },
  { cc: 'GY', name: "Guyana", region: "LATIN_AMERICA" },
  { cc: 'HT', name: "Haití", region: "LATIN_AMERICA" },
  { cc: 'HN', name: "Honduras", region: "LATIN_AMERICA" },
  { cc: 'HU', name: "Hungría", region: "EUROPE" },
  { cc: 'IN', name: "India", region: "ASIA" },
  { cc: 'ID', name: "Indonesia", region: "ASIA" },
  { cc: 'IQ', name: "Irak", region: "ASIA" },
  { cc: 'IE', name: "Irlanda", region: "EUROPE" },
  { cc: 'IR', name: "Irán", region: "ASIA" },
  { cc: 'BV', name: "Isla Bouvet", region: "ANTARCTICA" },
  { cc: 'NF', name: "Isla Norfolk", region: "OCEANIA" },
  { cc: 'IM', name: "Isla de Man", region: "EUROPE" },
  { cc: 'CX', name: "Isla de Navidad", region: "ASIA" },
  { cc: 'IS', name: "Islandia", region: "EUROPE" },
  { cc: 'AX', name: "Islas Aland", region: "EUROPE" },
  { cc: 'KY', name: "Islas Caimán", region: "LATIN_AMERICA" },
  { cc: 'CC', name: "Islas Cocos", region: "ASIA" },
  { cc: 'CK', name: "Islas Cook", region: "OCEANIA" },
  { cc: 'FO', name: "Islas Feroe", region: "EUROPE" },
  { cc: 'GS', name: "Islas Georgia del Sur y Sandwich del Sur", region: "ANTARCTICA" },
  { cc: 'HM', name: "Islas Heard y McDonald", region: "ANTARCTICA" },
  { cc: 'FK', name: "Islas Malvinas", region: "LATIN_AMERICA" },
  { cc: 'MP', name: "Islas Marianas del Norte", region: "OCEANIA" },
  { cc: 'MH', name: "Islas Marshall", region: "OCEANIA" },
  { cc: 'PN', name: "Islas Pitcairn", region: "OCEANIA" },
  { cc: 'SB', name: "Islas Salomón", region: "OCEANIA" },
  { cc: 'TC', name: "Islas Turcas y Caicos", region: "LATIN_AMERICA" },
  { cc: 'VG', name: "Islas Vírgenes Británicas", region: "LATIN_AMERICA" },
  { cc: 'VI', name: "Islas Vírgenes de EE. UU.", region: "LATIN_AMERICA" },
  { cc: 'UM', name: "Islas menores alejadas de EE. UU.", region: "OCEANIA" },
  { cc: 'IL', name: "Israel", region: "EUROPE" },
  { cc: 'IT', name: "Italia", region: "EUROPE" },
  { cc: 'JM', name: "Jamaica", region: "LATIN_AMERICA" },
  { cc: 'JP', name: "Japón", region: "ASIA" },
  { cc: 'JE', name: "Jersey", region: "EUROPE" },
  { cc: 'JO', name: "Jordania", region: "ASIA" },
  { cc: 'KZ', name: "Kazajistán", region: "EUROPE" },
  { cc: 'KE', name: "Kenia", region: "AFRICA" },
  { cc: 'KG', name: "Kirguistán", region: "EUROPE" },
  { cc: 'KI', name: "Kiribati", region: "OCEANIA" },
  { cc: 'XK', name: "Kosovo", region: "EUROPE" },
  { cc: 'KW', name: "Kuwait", region: "ASIA" },
  { cc: 'LA', name: "Laos", region: "ASIA" },
  { cc: 'LS', name: "Lesoto", region: "AFRICA" },
  { cc: 'LV', name: "Letonia", region: "EUROPE" },
  { cc: 'LR', name: "Liberia", region: "AFRICA" },
  { cc: 'LY', name: "Libia", region: "AFRICA" },
  { cc: 'LI', name: "Liechtenstein", region: "EUROPE" },
  { cc: 'LT', name: "Lituania", region: "EUROPE" },
  { cc: 'LU', name: "Luxemburgo", region: "EUROPE" },
  { cc: 'LB', name: "Líbano", region: "ASIA" },
  { cc: 'MK', name: "Macedonia del Norte", region: "EUROPE" },
  { cc: 'MG', name: "Madagascar", region: "AFRICA" },
  { cc: 'MY', name: "Malasia", region: "ASIA" },
  { cc: 'MW', name: "Malaui", region: "AFRICA" },
  { cc: 'MV', name: "Maldivas", region: "ASIA" },
  { cc: 'ML', name: "Mali", region: "AFRICA" },
  { cc: 'MT', name: "Malta", region: "EUROPE" },
  { cc: 'MA', name: "Marruecos", region: "AFRICA" },
  { cc: 'MQ', name: "Martinica", region: "LATIN_AMERICA" },
  { cc: 'MU', name: "Mauricio", region: "AFRICA" },
  { cc: 'MR', name: "Mauritania", region: "AFRICA" },
  { cc: 'YT', name: "Mayotte", region: "AFRICA" },
  { cc: 'FM', name: "Micronesia", region: "OCEANIA" },
  { cc: 'MD', name: "Moldavia", region: "EUROPE" },
  { cc: 'MN', name: "Mongolia", region: "ASIA" },
  { cc: 'ME', name: "Montenegro", region: "EUROPE" },
  { cc: 'MS', name: "Montserrat", region: "LATIN_AMERICA" },
  { cc: 'MZ', name: "Mozambique", region: "AFRICA" },
  { cc: 'MM', name: "Myanmar (Birmania)", region: "ASIA" },
  { cc: 'MX', name: "México", region: "LATIN_AMERICA" },
  { cc: 'MC', name: "Mónaco", region: "EUROPE" },
  { cc: 'NA', name: "Namibia", region: "AFRICA" },
  { cc: 'NR', name: "Nauru", region: "OCEANIA" },
  { cc: 'NP', name: "Nepal", region: "ASIA" },
  { cc: 'NI', name: "Nicaragua", region: "LATIN_AMERICA" },
  { cc: 'NG', name: "Nigeria", region: "AFRICA" },
  { cc: 'NU', name: "Niue", region: "OCEANIA" },
  { cc: 'NO', name: "Noruega", region: "EUROPE" },
  { cc: 'NC', name: "Nueva Caledonia", region: "OCEANIA" },
  { cc: 'NZ', name: "Nueva Zelanda", region: "OCEANIA" },
  { cc: 'NE', name: "Níger", region: "AFRICA" },
  { cc: 'OM', name: "Omán", region: "ASIA" },
  { cc: 'PK', name: "Pakistán", region: "ASIA" },
  { cc: 'PW', name: "Palaos", region: "OCEANIA" },
  { cc: 'PA', name: "Panamá", region: "LATIN_AMERICA" },
  { cc: 'PG', name: "Papúa Nueva Guinea", region: "OCEANIA" },
  { cc: 'PY', name: "Paraguay", region: "LATIN_AMERICA" },
  { cc: 'NL', name: "Países Bajos", region: "EUROPE" },
  { cc: 'PE', name: "Perú", region: "LATIN_AMERICA" },
  { cc: 'PF', name: "Polinesia Francesa", region: "OCEANIA" },
  { cc: 'PL', name: "Polonia", region: "EUROPE" },
  { cc: 'PT', name: "Portugal", region: "EUROPE" },
  { cc: 'PR', name: "Puerto Rico", region: "LATIN_AMERICA" },
  { cc: 'HK', name: "RAE de Hong Kong (China)", region: "ASIA" },
  { cc: 'MO', name: "RAE de Macao (China)", region: "ASIA" },
  { cc: 'GB', name: "Reino Unido", region: "EUROPE" },
  { cc: 'CF', name: "República Centroafricana", region: "AFRICA" },
  { cc: 'CD', name: "República Democrática del Congo", region: "AFRICA" },
  { cc: 'DO', name: "República Dominicana", region: "LATIN_AMERICA" },
  { cc: 'RE', name: "Reunión", region: "AFRICA" },
  { cc: 'RW', name: "Ruanda", region: "AFRICA" },
  { cc: 'RO', name: "Rumanía", region: "EUROPE" },
  { cc: 'RU', name: "Rusia", region: "EUROPE" },
  { cc: 'WS', name: "Samoa", region: "OCEANIA" },
  { cc: 'AS', name: "Samoa Americana", region: "OCEANIA" },
  { cc: 'BL', name: "San Bartolomé", region: "LATIN_AMERICA" },
  { cc: 'KN', name: "San Cristóbal y Nieves", region: "LATIN_AMERICA" },
  { cc: 'SM', name: "San Marino", region: "EUROPE" },
  { cc: 'MF', name: "San Martín", region: "LATIN_AMERICA" },
  { cc: 'PM', name: "San Pedro y Miquelón", region: "NORTH_AMERICA" },
  { cc: 'VC', name: "San Vicente y las Granadinas", region: "LATIN_AMERICA" },
  { cc: 'SH', name: "Santa Elena", region: "AFRICA" },
  { cc: 'LC', name: "Santa Lucía", region: "LATIN_AMERICA" },
  { cc: 'ST', name: "Santo Tomé y Príncipe", region: "AFRICA" },
  { cc: 'SN', name: "Senegal", region: "AFRICA" },
  { cc: 'RS', name: "Serbia", region: "EUROPE" },
  { cc: 'SC', name: "Seychelles", region: "AFRICA" },
  { cc: 'SL', name: "Sierra Leona", region: "AFRICA" },
  { cc: 'SG', name: "Singapur", region: "ASIA" },
  { cc: 'SX', name: "Sint Maarten", region: "LATIN_AMERICA" },
  { cc: 'SY', name: "Siria", region: "ASIA" },
  { cc: 'SO', name: "Somalia", region: "AFRICA" },
  { cc: 'LK', name: "Sri Lanka", region: "ASIA" },
  { cc: 'ZA', name: "Sudáfrica", region: "AFRICA" },
  { cc: 'SD', name: "Sudán", region: "AFRICA" },
  { cc: 'SS', name: "Sudán del Sur", region: "AFRICA" },
  { cc: 'SE', name: "Suecia", region: "EUROPE" },
  { cc: 'CH', name: "Suiza", region: "EUROPE" },
  { cc: 'SR', name: "Surinam", region: "LATIN_AMERICA" },
  { cc: 'SJ', name: "Svalbard y Jan Mayen", region: "EUROPE" },
  { cc: 'EH', name: "Sáhara Occidental", region: "AFRICA" },
  { cc: 'TH', name: "Tailandia", region: "ASIA" },
  { cc: 'TW', name: "Taiwán", region: "ASIA" },
  { cc: 'TZ', name: "Tanzania", region: "AFRICA" },
  { cc: 'TJ', name: "Tayikistán", region: "EUROPE" },
  { cc: 'IO', name: "Territorio Británico del Océano Índico", region: "ASIA" },
  { cc: 'TF', name: "Territorios Australes Franceses", region: "ANTARCTICA" },
  { cc: 'PS', name: "Territorios Palestinos", region: "ASIA" },
  { cc: 'TL', name: "Timor-Leste", region: "ASIA" },
  { cc: 'TG', name: "Togo", region: "AFRICA" },
  { cc: 'TK', name: "Tokelau", region: "OCEANIA" },
  { cc: 'TO', name: "Tonga", region: "OCEANIA" },
  { cc: 'TT', name: "Trinidad y Tobago", region: "LATIN_AMERICA" },
  { cc: 'TM', name: "Turkmenistán", region: "EUROPE" },
  { cc: 'TR', name: "Turquía", region: "EUROPE" },
  { cc: 'TV', name: "Tuvalu", region: "OCEANIA" },
  { cc: 'TN', name: "Túnez", region: "AFRICA" },
  { cc: 'UA', name: "Ucrania", region: "EUROPE" },
  { cc: 'UG', name: "Uganda", region: "AFRICA" },
  { cc: 'UY', name: "Uruguay", region: "LATIN_AMERICA" },
  { cc: 'UZ', name: "Uzbekistán", region: "EUROPE" },
  { cc: 'VU', name: "Vanuatu", region: "OCEANIA" },
  { cc: 'VE', name: "Venezuela", region: "LATIN_AMERICA" },
  { cc: 'VN', name: "Vietnam", region: "ASIA" },
  { cc: 'WF', name: "Wallis y Futuna", region: "OCEANIA" },
  { cc: 'YE', name: "Yemen", region: "ASIA" },
  { cc: 'DJ', name: "Yibuti", region: "AFRICA" },
  { cc: 'ZM', name: "Zambia", region: "AFRICA" },
  { cc: 'ZW', name: "Zimbabue", region: "AFRICA" },
];

export const COUNTRY_NAME: Record<string, string> = Object.fromEntries(COUNTRIES.map((c) => [c.cc, c.name]));
